export const CLIENT_ID = 'VXR00PBZRJNTGINQRHDEB5T0GWZOTOXQP42MAU4MGVWP00WB';

export const CLIENT_SECRET = '2BVVYFFL5KEYWKW240YKHHD5YNCA4UXGZULDALAKUFFZ31D4';

export const MAP_KEY = 'AIzaSyCFJfDwa-JEntdf_ABHEmuF1QS27rDJaao';
